In [1]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'Decision Tree Algorithm.ipynb', 'groupStudy.csv']


In [2]:
import numpy as np
import pandas as pd

In [3]:
#import our dataset

data = pd.read_csv('groupStudy.csv')

In [4]:
data.head()

Position  Hours of study  Marks scored
0  Group-1               1            45
1  Group-2               2            50
2  Group-3               3            60
3  Group-4               4            80
4  Group-5               5           110

In [8]:
X = data.iloc[:, 1:2].values

In [9]:
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]], dtype=int64)

In [10]:
y = data.iloc[:,2].values

In [11]:
y

array([  45,   50,   60,   80,  110,  150,  200,  300,  500, 1000],
      dtype=int64)

In [12]:
# fit data into decision tree regressor

from sklearn.tree import DecisionTreeRegressor


In [13]:
regressor = DecisionTreeRegressor()
regressor.fit(X,y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [24]:
y_predicted = regressor.predict(6.6)

In [25]:
y_predicted

array([200.])