# Exercise file for Numpy

In [3]:
myList = [1,2,3,4,5]

In [4]:
myList

[1, 2, 3, 4, 5]

In [5]:
import numpy as np #from package install subpackage

In [6]:
myOneDArray = np.array(myList)

In [8]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
myOneDArray

array([1, 2, 3, 4, 5])

In [9]:
myMultiList = [[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]]

In [10]:
myTwoDArray = np.array(myMultiList)

In [11]:
myTwoDArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Generating some random data

In [17]:
data = np.random.rand(1)

In [18]:
data

array([0.82900257])

In [25]:
data = np.random.rand(10)

In [26]:
data

array([0.36092926, 0.32383724, 0.2200248 , 0.43218853, 0.44709585,
       0.76966457, 0.72667657, 0.92827217, 0.4269612 , 0.52468689])

In [27]:
data = np.random.rand(2,3)

In [28]:
data

array([[0.76795306, 0.6291028 , 0.72911056],
       [0.03831335, 0.79445286, 0.15645445]])

In [29]:
data.shape

(2, 3)

In [30]:
data.dtype

dtype('float64')

#### Arithmetic with NumPy Arrays


In [31]:
arr = np.array([[1,2,3],[4,5,6]])

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [34]:
arr + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [35]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [36]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [37]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [38]:
arr2 = np.array([[0,4,1],[7,2,12]])

In [39]:
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [40]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [41]:
arr = np.arange(10)

In [42]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr[5]

5

In [44]:
arr[4:9]

array([4, 5, 6, 7, 8])

In [45]:
arr[3:6] = 12

In [46]:
arr

array([ 0,  1,  2, 12, 12, 12,  6,  7,  8,  9])

In [51]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [52]:
data = np.random.randn(7, 4)

In [53]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [54]:
data

array([[ 0.81974357,  1.01744239, -0.47505867, -0.78448256],
       [-0.19497268, -0.3311273 ,  0.23210894, -1.06118737],
       [-0.43855022,  0.70652009,  0.57775801,  1.59954025],
       [ 0.2324721 ,  0.22838237,  0.19805845,  0.20724258],
       [-0.14782643,  0.4969013 , -0.63033468, -1.10717977],
       [ 1.07784167, -0.23030924, -0.90427981,  0.41007385],
       [ 0.45525456,  1.28860295,  0.3503931 ,  1.39661334]])

In [55]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [56]:
data[names == 'Bob']

array([[ 0.81974357,  1.01744239, -0.47505867, -0.78448256],
       [ 0.2324721 ,  0.22838237,  0.19805845,  0.20724258]])

In [57]:
data[names == 'Bob', 2:]

array([[-0.47505867, -0.78448256],
       [ 0.19805845,  0.20724258]])

In [58]:
data[names == 'Bob', 3]

array([-0.78448256,  0.20724258])

### We could have use != or ~ for negating the condition

In [59]:
data[~(names == 'Bob')]

array([[-0.19497268, -0.3311273 ,  0.23210894, -1.06118737],
       [-0.43855022,  0.70652009,  0.57775801,  1.59954025],
       [-0.14782643,  0.4969013 , -0.63033468, -1.10717977],
       [ 1.07784167, -0.23030924, -0.90427981,  0.41007385],
       [ 0.45525456,  1.28860295,  0.3503931 ,  1.39661334]])

In [60]:
data[names != 'Bob']

array([[-0.19497268, -0.3311273 ,  0.23210894, -1.06118737],
       [-0.43855022,  0.70652009,  0.57775801,  1.59954025],
       [-0.14782643,  0.4969013 , -0.63033468, -1.10717977],
       [ 1.07784167, -0.23030924, -0.90427981,  0.41007385],
       [ 0.45525456,  1.28860295,  0.3503931 ,  1.39661334]])

In [62]:
condition = names == 'Bob'

In [63]:
data[~condition]

array([[-0.19497268, -0.3311273 ,  0.23210894, -1.06118737],
       [-0.43855022,  0.70652009,  0.57775801,  1.59954025],
       [-0.14782643,  0.4969013 , -0.63033468, -1.10717977],
       [ 1.07784167, -0.23030924, -0.90427981,  0.41007385],
       [ 0.45525456,  1.28860295,  0.3503931 ,  1.39661334]])

In [64]:
mask = (names == 'Bob') | (names == 'Will')

In [65]:
mask

array([ True, False,  True,  True,  True, False, False])

In [66]:
data[mask]

array([[ 0.81974357,  1.01744239, -0.47505867, -0.78448256],
       [-0.43855022,  0.70652009,  0.57775801,  1.59954025],
       [ 0.2324721 ,  0.22838237,  0.19805845,  0.20724258],
       [-0.14782643,  0.4969013 , -0.63033468, -1.10717977]])

### To set all the negative values in data to 0

In [68]:
data[data < 0] = 0

In [69]:
data

array([[0.81974357, 1.01744239, 0.        , 0.        ],
       [0.        , 0.        , 0.23210894, 0.        ],
       [0.        , 0.70652009, 0.57775801, 1.59954025],
       [0.2324721 , 0.22838237, 0.19805845, 0.20724258],
       [0.        , 0.4969013 , 0.        , 0.        ],
       [1.07784167, 0.        , 0.        , 0.41007385],
       [0.45525456, 1.28860295, 0.3503931 , 1.39661334]])

## Get a matrix of all 1's of size 3,4 - Assingment 

In [71]:
np.linspace(0,5, 15) #Linear Space

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [70]:
np.identity(4) #Identity Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Normal Distribution

In [72]:
np.random.randn(5,5)

array([[ 8.88997866e-01, -5.07064482e-01,  8.33528656e-01,
        -3.35824755e-01,  7.91297235e-01],
       [ 1.30019277e+00,  2.52559632e-01, -4.80230961e-01,
         5.79319386e-01, -1.69012709e+00],
       [-1.66897495e-01,  1.89850535e+00,  1.69427478e+00,
         3.00871619e-01, -1.61379832e+00],
       [-4.73080962e-01, -7.01343540e-01,  4.25439497e-01,
         1.21381295e-01,  1.15898911e+00],
       [ 1.94993982e+00,  9.05088976e-01,  4.31843759e-05,
        -1.43069469e+00, -6.09919545e-01]])

In [80]:
np.random.randint(1,50)# Generating random number between range 1,50

30

In [85]:
np.random.randint(1,100)

48

In [86]:
myNum = np.arange(25)

In [87]:
myNum

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [88]:
myReshaped = myNum.reshape(5,5)

In [89]:
myReshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [90]:
myReshape = myNum.reshape(4,4)

ValueError: cannot reshape array of size 25 into shape (4,4)

In [91]:
myReshaped.max()

24

In [92]:
pwd

'C:\\Users\\Mayank'

In [93]:
cd D:\\

D:\
