# Intermediate Stuff with Numpy

In [1]:
import numpy as np

In [2]:
myArray = np.arange(10,21)

In [3]:
myArray

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
myArray[1]

11

In [5]:
myArray[-1]

20

In [6]:
myArray[1:4]

array([11, 12, 13])

In [7]:
myArray[:4]

array([10, 11, 12, 13])

In [8]:
myArray[:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
myArray[::-1] # Reversing

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [10]:
partArray = myArray[:4]

In [11]:
partArray

array([10, 11, 12, 13])

In [12]:
partArray[:] = 50

In [13]:
partArray

array([50, 50, 50, 50])

In [14]:
myArray #Changed #Reference of original array

array([50, 50, 50, 50, 14, 15, 16, 17, 18, 19, 20])

In [15]:
copyArray = myArray.copy()

In [16]:
copyArray

array([50, 50, 50, 50, 14, 15, 16, 17, 18, 19, 20])

In [17]:
copyArray[:4] = 10

In [18]:
copyArray

array([10, 10, 10, 10, 14, 15, 16, 17, 18, 19, 20])

In [19]:
myArray

array([50, 50, 50, 50, 14, 15, 16, 17, 18, 19, 20])

## Part 2 - 2d Array

In [20]:
my2dArray = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

In [21]:
my2dArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
my2dArray[1]

array([4, 5, 6])

In [23]:
my2dArray[1][2]

6

In [24]:
my2dArray[1,2]

6

In [25]:
# my2dArray['row','column'] 

In [26]:
my2dArray[:2 , 1:]

array([[2, 3],
       [5, 6]])

In [27]:
my2dArray[:3 , 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

### Assingment Select (1,2 & 4,5) (4,5 & 7,8) (5,6 & 8,9)

## Part 3

In [28]:
newArray = np.arange(2,20)

In [29]:
newArray

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [30]:
newArray[newArray > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
newArray > 10

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

### Statical Operations

In [32]:
np.sqrt(newArray)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
       4.12310563, 4.24264069, 4.35889894])

In [33]:
np.mean(newArray)

10.5

In [34]:
np.var(newArray)

26.916666666666668

In [35]:
np.std(newArray)

5.188127472091127

In [36]:
A = np.array([1,2,3])

In [37]:
B = np.array([5,6,7])

In [38]:
np.cross(A,B)

array([-4,  8, -4])

In [39]:
np.dot(A,B)

38

In [40]:
x = np.arange(4)

In [41]:
x

array([0, 1, 2, 3])

In [42]:
x = np.arange(4).reshape(2,2)

In [43]:
x

array([[0, 1],
       [2, 3]])

In [44]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [45]:
x = np.ones((1,2,3))

In [46]:
x

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [47]:
np.transpose(x,(1,0,2)).shape

(2, 1, 3)

In [48]:
x = np.arange(8)

In [49]:
np.array_split(x,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

In [50]:
random.seed(0)

NameError: name 'random' is not defined

In [ ]:
random.randint(1,10)

In [ ]:
rng = np.random.RandomState(0)

In [ ]:
rng.randn(10)

In [ ]:
rng.randn(11)

In [ ]:
#Example : Random Walks

In [ ]:
import random

In [ ]:
pos = 0
walk = [pos]
steps = 1000
for i in range(steps):
    if random.randint(0, 1):
        step = 1
    else:
        step = -1
    pos = pos + step
    walk.append(pos)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot(walk[:100])